name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy AWS app
    runs-on: ubuntu-latest
    container: node:13.10
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Deploy gatsby starter
        env:
          AWS_DEFAULT_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_IAM_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_IAM_SECRET_KEY }}
        run: |
          aws cloudformation deploy --template-file template.yml --stack-name sys-gatsby-starter --parameter-overrides PersonalAccessToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} --debug
