name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy AWS app
    runs-on: ubuntu-latest
    container: node:13.10
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Deploy to AWS
        uses: university-of-york/aws-sam-deploy-action@v1.1.1
        env:
          TEMPLATE: 'template.yml'
          AWS_STACK_NAME: 'sys-gatsby-starter'
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_GLOBAL_ARTIFACT_BUCKET }}
          ROLE_ARN: 'arn:aws:iam::326340845860:role/GithubActionsDeploymentRole'
          PARAMETER_OVERRIDES: PersonalAccessToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}
