name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy AWS app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Deploy to AWS
        uses: docker://ghcr.io/university-of-york/aws-sam-deploy-action:latest
        env:
          TEMPLATE: 'template.yml'
          AWS_STACK_NAME: 'sys-gatsby-starter'
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_GLOBAL_ARTIFACT_BUCKET }}
          ROLE_ARN: 'arn:aws:iam::326340845860:role/GithubActionsDeploymentRole'
          CAPABILITIES: 'CAPABILITY_IAM'
          OVERRIDES: PersonalAccessToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAGS: group=SYS project=GATSBY status=prod pushed_by=github defined_in=cloudformation user=pgg505
          FORCE_UPLOAD: true
