name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy AWS app
    runs-on: ubuntu-latest
    container: node:13.10
    if: "contains(github.event.head_commit.message, '(deploy)')"

    # Only runs if git commit message contains "(deploy)"; see README for details.
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Build front end using Gatsby
        run: |
          npm install -g gatsby-cli
          npm install
          gatsby build
      - name: Deploy to AWS
        uses: university-of-york/aws-sam-deploy-action@v1.1.1
        env:
          TEMPLATE: 'template.yml'
          AWS_STACK_NAME: 'sys-gatsby-starter'
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_GLOBAL_ARTIFACT_BUCKET }}
          ROLE_ARN: 'arn:aws:iam::326340845860:role/GithubActionsDeploymentRole'
      - name: Deploy Gatsby app
        env:
          AWS_DEFAULT_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          stack=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          bucket=$(aws cloudformation describe-stacks --stack-name $stack --output text | grep FrontendBucketIdentifier | awk '{ print $3 }')
          aws s3 cp frontend/public s3://${bucket} --recursive 
